### ISSUE TITLE
Add valid links to Github and Support Buttons in Mobile Sidebar menu

### ISSUE THREAD

**Issue by harsh3dev** [harsh3dev/DevMatchups#15]
### Issue Title
Add valid links to Github and Support Buttons in Mobile Sidebar menu

---

### Description
The mobile sidebar menu currently has placeholders for the **GitHub** and **Support** buttons. These buttons should redirect to the appropriate external links.

---

### Expected Behavior
- **GitHub button** should redirect users to the repository's GitHub page. 
       - use this link: https://github.com/harsh3dev/devmatchups
- **Support button** should open the support page or a relevant external link. 
        - use this email: devmatchups@gmail.com

---

### Current Behavior
- Both buttons are not functional and don't redirect to any links.

---

### Steps to Reproduce
1. Open the application on a mobile device.
2. Click on the sidebar menu.
3. Click the **GitHub** or **Support** buttons.

---

### Possible Solution
- Update the buttons with the following valid links:
  - **GitHub**: [https://github.com/harsh3dev/devmatchups](https://github.com/harsh3dev/devmatchups)
  - **Support**: devmatchups@gmail.com
  - `@/app/Navbar/Navbar.tsx` line: 208

---

### Context
This issue affects the user experience on the mobile version, leading to a lack of proper navigation to the repository or support page.

---

### Screenshots (if applicable)
- 
![image](https://github.com/user-attachments/assets/6ca59c11-4259-4ca2-80ca-bd7da7d46a93)

---

### Additional Information
Please make sure the solution works across various mobile devices and screen sizes.

---

**Comment by gandholi-kumar** [comment]
@harsh3dev I'm interested in it, can you assign it to me?
Can you let me know 

- Are these GitHub and Support are hardcoded values?
- Should they redirect in new page or same page?

GitHub: https://github.com/harsh3dev/devmatchups
Support: [devmatchups@gmail.com](mailto:devmatchups@gmail.com)

**Comment by harsh3dev** [comment]
Hi, these are links which are predefined and should be redirected to new page.
@gandholi-kumar

**Comment by gandholi-kumar** [comment]
Thank you for information, can you assign it to me so that I can start working on it.

**Comment by harsh3dev** [comment]
> Thank you for information, can you assign it to me so that I can start working on it.

You have been assigned

**Comment by Vishal-Gori** [comment]
I have resolved this issue #18 could accept my PR @harsh3dev

![image](https://github.com/user-attachments/assets/a719186b-10b1-49f0-a8f1-c55c4826e352)

**Comment by Vishal-Gori** [comment]
@harsh3dev I have made these changes and raised a PR, could you please verify and accept. #20
