### ISSUE TITLE
Extra left margin on larger screens in "Explore Hackathons" page leading to unnecessary horizontal scroll

### ISSUE THREAD

**Issue by harsh3dev** [harsh3dev/DevMatchups#16]
### Issue Title
Extra left margin on larger screens in "Explore Hackathons" page leading to unnecessary horizontal scroll

---

### Description
On the "Explore Hackathons" page, an excessive left margin appears on larger screen sizes, causing unwanted horizontal scrolling. This affects the layout and user experience on desktop devices.

---

### Expected Behavior
- The layout should be properly aligned, with no unnecessary horizontal scroll.
- The content should adjust to the screen size without extra margins on larger screens.

---

### Current Behavior
- On larger screens, there is a visible left margin that causes unnecessary horizontal scroll on the "Explore Hackathons" page.
- An extra `margin-left: 40px` is there which should be removed

---

### Steps to Reproduce
1. Open the application on a desktop device with a large screen.
2. Navigate to the "Explore Hackathons" page.
3. Observe the layout and check for horizontal scrolling.

---

### Possible Solution
- Review the CSS for the page's container or wrapper elements, specifically for larger screen sizes.
- Remove the `margin-left` from the header buttons in `@/app/(dashboard)/(routes)/hackathons/page.tsx` line: 73
---

### Context
This issue disrupts the user experience on larger screens by causing unnecessary scrolling and layout misalignment.

---

### Screenshots (if applicable)
![Screenshot 2024-10-01 105537](https://github.com/user-attachments/assets/02deb860-ff70-42b8-919e-a9a7e76bb579)

---

### Additional Information
Please test the solution on multiple screen sizes and devices to ensure consistent behavior.

---

**Comment by alberturria** [comment]
Hey! :wave: 
I would be down to try to tackle this issue :slightly_smiling_face: could you assign it to me?

**Comment by mumtazmumtazfb** [comment]
Can I please solve this? Would you be able to please assign it to me?

**Comment by harsh3dev** [comment]
> Hey! 👋 I would be down to try to tackle this issue 🙂 could you assign it to me?

I have assigned you the issue
