### ISSUE TITLE
Incorrect Footer Icon Links 

### ISSUE THREAD

**Issue by nilesh-fatfatwale** [harsh3dev/DevMatchups#21]
Issue Title
Missing  footer links

Description
In the footer, all 3 icons redirected to the original website the links should replace

Expected Behavior
The Twitter icon should redirect to the official Twitter page

The GitHub icon should redirect to the official GitHub repository

ProductHunt doesn't know the actual use case here (comment for further contribution)

Current Behavior
all the 3 icons are only redirected to the same current website

Steps to Reproduce
1. Open the application on both desktop/mobile devices.
2. Navigate to the "footer section".
3. check out all 3 icons which are wrong links

Possible Solution
go to the footer section and change the actual links 

Context
this issue prevents the users from navigating external resources

![footer_links](https://github.com/user-attachments/assets/21710fd9-c5aa-42bc-8997-1df7aeb647e9)

![footer_issue](https://github.com/user-attachments/assets/aaceb66d-6c72-4832-92d0-5de81cc85372)

I am ready to tackle this issue 🚀

**Comment by Nilesh270** [comment]
Could you plz assign this issue to me!
i would love to resolve this issue
