### ISSUE TITLE
Update Footer Social Media icon Links

### ISSUE THREAD

**Issue by harsh3dev** [harsh3dev/DevMatchups#23]
### Description
The social media icons in the footer currently redirect to null links. The links should be updated to the appropriate social media profiles.

---

### Expected Behavior
- Each social icon (e.g., GitHub, Twitter, ProductHunt) should redirect to the correct and updated social media profile or page. (should be opened in new tab)

---

### Current Behavior
- The current links are either pointing to the home page.

---

### Steps to Reproduce
1. Navigate to the footer section of any page.
2. Click on each social media icon.
3. Observe the redirection.

---

### Possible Solution
- Replace the existing links with updated URLs:
  - *GitHub*: [https://github.com/harsh3dev/devmatchups](https://github.com/harsh3dev/devmatchups)
  - *Twitter*: [https://twitter.com/devmatchups](https://twitter.com/devmatchups)
  - *ProductHunt*: [https://www.producthunt.com/posts/devmatchups](https://www.producthunt.com/posts/devmatchups)

---

### Additional Information
- Ensure that all links open in a new tab (i.e., target="_blank").
- Use Next.js <Link> component and not the native <a> tag.

**Comment by Rohit-554** [comment]
Hi Harsh, I want to raise a pr on this

**Comment by 720Florian** [comment]
> Hi Harsh, I want to raise a pr on this

I have already solved the problem

**Comment by subhamagarrwal** [comment]
hi could you assign me this task
