### ISSUE TITLE
Implement Shimmer UI Loading Effect on the Hackathon ID Page

### ISSUE THREAD

**Issue by Yashgupta9330** [harsh3dev/DevMatchups#27]
Description:
The current loading animation on the Hackathon ID page is not visually appealing. Please remove the existing loading indicator and implement a Shimmer UI loading effect instead. This will enhance the user experience by providing a smoother and more modern loading transition.

You can refer to the attached video for a demonstration of the current loading state.

https://github.com/user-attachments/assets/73b25261-ee37-4a3b-8726-2dc81d1cbc34

**Comment by akadeepesh** [comment]
Hi @Yashgupta9330 I'm willing to work on this. Please assign it to me. Also if you can just provide me the path of current loading page it will save some time of mine. Thank you.

**Comment by vai-sys** [comment]
Hi @Yashgupta9330  Please assign me this issue

**Comment by Yashgupta9330** [comment]
@akadeepesh this is the path where you have to change app/(dashboard)/(routes)/teams/[id]/page.tsx                
![image](https://github.com/user-attachments/assets/938ad1cc-8b02-4932-886d-d40650034c9a)
You have to change this code you can see in the image

**Comment by akadeepesh** [comment]
Great @Yashgupta9330 I'm on it
